"""empty message

Revision ID: 594092b73aaf
Revises: 7b341695f43f
Create Date: 2022-09-30 18:01:22.043220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594092b73aaf'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('atk', sa.Integer(), nullable=False),
    sa.Column('defe', sa.Integer(), nullable=False),
    sa.Column('sDf', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pokemon_id'),
    sa.UniqueConstraint('pokemon_id')
    )
    op.create_table('favorites',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('pokemontype', sa.String(length=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id'),
    sa.UniqueConstraint('pokemon_id')
    )
    op.create_table('pokemon__fusion',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pokemon_rostro_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_cuerpo_id', sa.Integer(), nullable=False),
    sa.Column('atk', sa.Integer(), nullable=False),
    sa.Column('defe', sa.Integer(), nullable=False),
    sa.Column('sDf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_cuerpo_id'], ['pokemon.pokemon_id'], ),
    sa.ForeignKeyConstraint(['pokemon_rostro_id'], ['pokemon.pokemon_id'], ),
    sa.PrimaryKeyConstraint('pokemon_id'),
    sa.UniqueConstraint('pokemon_id')
    )
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('img', sa.String(length=300), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'img')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'username')
    op.drop_table('pokemon__fusion')
    op.drop_table('favorites')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
