"""empty message

Revision ID: b6b6265d613a
Revises: 3740f72596d2
Create Date: 2022-11-09 19:34:07.591026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b6265d613a'
down_revision = '3740f72596d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ability', ['ability_id'])
    op.create_unique_constraint(None, 'favorites', ['pokemon_id'])
    op.create_unique_constraint(None, 'item', ['item_id'])
    op.create_unique_constraint(None, 'moves', ['move_id'])
    op.create_unique_constraint(None, 'nature', ['nature_id'])
    op.create_unique_constraint(None, 'pokemon', ['pokemon_id'])
    op.create_unique_constraint(None, 'pokemon__ability', ['id'])
    op.create_unique_constraint(None, 'pokemon__fusion__ability', ['id'])
    op.create_unique_constraint(None, 'pokemon__fusion__move', ['id'])
    op.create_unique_constraint(None, 'pokemon__fusion__nature', ['id'])
    op.create_unique_constraint(None, 'pokemon__move', ['id'])
    op.create_unique_constraint(None, 'pokemon_fusion', ['pokemon_id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'pokemon_fusion', type_='unique')
    op.drop_constraint(None, 'pokemon__move', type_='unique')
    op.drop_constraint(None, 'pokemon__fusion__nature', type_='unique')
    op.drop_constraint(None, 'pokemon__fusion__move', type_='unique')
    op.drop_constraint(None, 'pokemon__fusion__ability', type_='unique')
    op.drop_constraint(None, 'pokemon__ability', type_='unique')
    op.drop_constraint(None, 'pokemon', type_='unique')
    op.drop_constraint(None, 'nature', type_='unique')
    op.drop_constraint(None, 'moves', type_='unique')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_constraint(None, 'favorites', type_='unique')
    op.drop_constraint(None, 'ability', type_='unique')
    # ### end Alembic commands ###
