"""empty message

Revision ID: dd5b70c2af48
Revises: b0b252ccd40b
Create Date: 2022-11-09 15:18:20.101380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd5b70c2af48'
down_revision = 'b0b252ccd40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ability', ['ability_id'])
    op.create_unique_constraint(None, 'favorites', ['pokemon_id'])
    op.create_unique_constraint(None, 'item', ['item_id'])
    op.create_unique_constraint(None, 'moves', ['move_id'])
    op.create_unique_constraint(None, 'nature', ['item_id'])
    op.create_unique_constraint(None, 'pokemon', ['pokemon_id'])
    op.create_unique_constraint(None, 'pokemon__ability', ['id'])
    op.add_column('pokemon__fusion', sa.Column('pokemon_id_fusion', sa.Integer(), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('id_fusion', sa.Integer(), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('order_fusion', sa.Integer(), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('name_fusion', sa.String(length=120), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('description_fusion', sa.String(length=300), nullable=True))
    op.add_column('pokemon__fusion', sa.Column('img_fusion', sa.String(length=201), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('type_fusion', postgresql.ARRAY(sa.String(length=300)), nullable=True))
    op.add_column('pokemon__fusion', sa.Column('weight_fusion', sa.Integer(), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('height_fusion', sa.Integer(), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('ps_fusion', sa.Integer(), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('spd_fusion', sa.Integer(), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('sp_defens_fusion', sa.Integer(), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('sp_atk_fusion', sa.Integer(), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('defens_fusion', sa.Integer(), nullable=False))
    op.add_column('pokemon__fusion', sa.Column('atk_fusion', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'pokemon__fusion', ['pokemon_id_fusion'])
    op.create_unique_constraint(None, 'pokemon__fusion', ['id_fusion'])
    op.drop_column('pokemon__fusion', 'name')
    op.drop_column('pokemon__fusion', 'atk')
    op.drop_column('pokemon__fusion', 'pokemon_id')
    op.drop_column('pokemon__fusion', 'sDf')
    op.drop_column('pokemon__fusion', 'defe')
    op.create_unique_constraint(None, 'pokemon__move', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'pokemon__move', type_='unique')
    op.add_column('pokemon__fusion', sa.Column('defe', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pokemon__fusion', sa.Column('sDf', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pokemon__fusion', sa.Column('pokemon_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('pokemon__fusion', sa.Column('atk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pokemon__fusion', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pokemon__fusion', type_='unique')
    op.drop_constraint(None, 'pokemon__fusion', type_='unique')
    op.drop_column('pokemon__fusion', 'atk_fusion')
    op.drop_column('pokemon__fusion', 'defens_fusion')
    op.drop_column('pokemon__fusion', 'sp_atk_fusion')
    op.drop_column('pokemon__fusion', 'sp_defens_fusion')
    op.drop_column('pokemon__fusion', 'spd_fusion')
    op.drop_column('pokemon__fusion', 'ps_fusion')
    op.drop_column('pokemon__fusion', 'height_fusion')
    op.drop_column('pokemon__fusion', 'weight_fusion')
    op.drop_column('pokemon__fusion', 'type_fusion')
    op.drop_column('pokemon__fusion', 'img_fusion')
    op.drop_column('pokemon__fusion', 'description_fusion')
    op.drop_column('pokemon__fusion', 'name_fusion')
    op.drop_column('pokemon__fusion', 'order_fusion')
    op.drop_column('pokemon__fusion', 'id_fusion')
    op.drop_column('pokemon__fusion', 'pokemon_id_fusion')
    op.drop_constraint(None, 'pokemon__ability', type_='unique')
    op.drop_constraint(None, 'pokemon', type_='unique')
    op.drop_constraint(None, 'nature', type_='unique')
    op.drop_constraint(None, 'moves', type_='unique')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_constraint(None, 'favorites', type_='unique')
    op.drop_constraint(None, 'ability', type_='unique')
    # ### end Alembic commands ###
